export const questions = [
    {
        id: 0,
        question: 'Condições para realização da avaliação',
        answers: [],
        complement: '',
    },
    {
        id: 1,
        question: 'Está descansado hoje?',
        answers: ['sim', 'não'],
        complement: 'Por quê?',
    },
    {
        id: 2,
        question: 'Dormiu bem esta noite?',
        answers: ['sim', 'não'],
        complement: 'Por quê?',
    },
    {
        id: 3,
        question: 'Está alimentado?',
        answers: ['sim', 'não'],
        complement: '',
    },
    {
        id: 4,
        question: 'Fez uso de bebida alcoolica nas últimas horas?',
        answers: ['sim', 'não'],
        complement: '',
    },
    {
        id: 5,
        question: 'Fez uso de alguma medicação ontem/hoje?',
        answers: ['sim', 'não'],
        complement: '',
    },
    {
        id: 6,
        question: 'Faz uso de lentes corretivas/óculos?',
        answers: ['sim', 'não'],
        complement: '',
    },
    {
        id: 7,
        question: 'Considera-se em boas condições para realização da avaliação psicológica?',
        answers: ['sim', 'não'],
        complement: 'Por quê?',
    },
    {
        id: 0,
        question: 'Histórico Familiar',
        answers: [],
        complement: '',
    },
    {
        id: 8,
        question: 'Estado Civil',
        answers: ['Divorciado', 'Viúvo', 'Solteiro', 'Casado', 'União Estável'],
        complement: '',
    },
    {
        id: 9,
        question: 'Possui filhos?',
        answers: ['Sim', 'Não'],
        complement: '',
    },
    {
        id: 10,
        question: '',
        answers: [],
        complement: 'Com quem você mora?',
    },
    {
        id: 11,
        question: 'Está enfrentando problemas familiares?',
        answers: ['Sim', 'Não'],
        complement: 'Quais?',
    },
    {
        id: 12,
        question: 'Possui irmãos?',
        answers: ['Sim', 'Não'],
        complement: 'Quantos?',
    },
    {
        id: 13,
        question: '',
        answers: [],
        complement: 'Como é seu relacionamento com sua família?',
    },
    {
        id: 14,
        question: 'Na família existe alguém que necessite de cuidados médicos ou psicológicos? ',
        answers: ['Sim', 'Não'],
        complement: 'Nota',
    },
    {
        id: 0,
        question: 'Vida Profissional',
        answers: [],
        complement: '',
    },
    {
        id: 15,
        question: 'Atualmente',
        answers: ['Aposentado', 'Desempregado', 'Nunca Trabalhou', 'Está Trabalhando'],
        complement: '',
    },
    {
        id: 16,
        question: '',
        answers: [],
        complement: 'Função Desempenhada? Há quanto tempo?',
    },
    {
        id: 17,
        question: 'Esta satisfeito com o que fez?',
        answers: ['Sim', 'Não'],
        complement: 'Por Quê?',
    },
    {
        id: 18,
        question: 'Trabalhando em que turno?',
        answers: ['Noturno', 'Diurno', 'Rodízio de turnos. Horário:'],
        complement: 'Nota',
    },
    {
        id: 19,
        question: 'Está afastado pelo INSS?',
        answers: ['Sim', 'Não'],
        complement: 'Por qual motivo?',
    },
    {
        id: 0,
        question: 'Histórico Escolar',
        answers: [],
        complement: '',
    },
    {
        id: 20,
        question: 'Escolaridade',
        answers: ['Superior Completo', 'Superior Incompleto', 'Médio Completo', 'Médio Incompleto', 'Fundamental Completo', 'Fundamental Incompleto', 'Primário', 'Analfabeto' ],
        complement: '',
    },
    {
        id: 21,
        question: 'Está estudando?',
        answers: ['Sim', 'Não'],
        complement: 'Parou há quanto tempo?',
    },
    {
        id: 22,
        question: 'Ensino:',
        answers: ['Regular', 'Supletivo', 'À distância'],
        complement: 'Nota',
    },
    {
        id: 0,
        question: 'Saúde',
        answers: [],
        complement: '',
    },
    {
        id: 23,
        question: 'Tem ou já teve problema de saúde com necessidade de acompanhamento médico/psicológico?',
        answers: ['Sim', 'Não'],
        complement: 'Qual?',
    },
    {
        id: 24,
        question: 'Faz uso de medicamentos?',
        answers: ['Sim', 'Não'],
        complement: 'Qual(is)?',
    },
    {
        id: 25,
        question: 'Possui deficiência?',
        answers: ['Visual', 'Física', 'Auditiva', 'Física', 'Não'],
        complement: 'Qual?',
    },
    {
        id: 26,
        question: 'Sente desmaios, tontura, mal estar, dores de cabeça constantes, crises convulsivas? ',
        answers: ['Sim', 'Não'],
        complement: '',
    },
    {
        id: 27,
        question: 'Já sofreu algum acidente, tombo, fratura, pancada na cabeça? ',
        answers: ['Sim', 'Não'],
        complement: '',
    },
    {
        id: 28,
        question: 'Pratica alguma atividade física?',
        answers: ['Sim', 'Não'],
        complement: 'Quais?',
    },
    {
        id: 0,
        question: 'Hábitos e conduta social',
        answers: [],
        complement: '',
    },
    {
        id: 29,
        question: 'Faz uso de cigarros?',
        answers: ['Sim', 'Não'],
        complement: 'Quantos por dia?',
    },
    {
        id: 30,
        question: 'É ex-fumante?',
        answers: ['Sim', 'Não'],
        complement: 'Há quanto tempo?',
    },
    {
        id: 31,
        question: 'Faz ingestão de café?',
        answers: ['Sim', 'Não'],
        complement: 'Frequencia:',
    },
    {
        id: 32,
        question: 'Faz uso de bebida álcoolica?',
        answers: ['Sim', 'Não'],
        complement: 'Quantidade/frequência:	',
    },
    {
        id: 33,
        question: 'Já usou ou usa algum tipo de droga? ',
        answers: ['Sim', 'Não'],
        complement: 'Qual/frequência: ',
    },
    {
        id: 34,
        question: ' Faz/fez tratamento para deixar de usar? ',
        answers: ['Sim', 'Não'],
        complement: 'Por quê?',
    },
    {
        id: 35,
        question: '',
        answers: [],
        complement: 'Quais são suas atividades de lazer, hobbies?',
    },
    {
        id: 36,
        question: 'Pratica alguma religião?',
        answers: ['Sim', 'Não'],
        complement: 'Qual/Frequência:',
    },
    {
        id: 37,
        question: 'Houve alguma mudança na sua rotina nas últimas semanas?',
        answers: ['Sim', 'Não'],
        complement: 'Nota',
    },
    {
        id: 38,
        question: 'Possui antecedente penal/criminal? ',
        answers: ['Sim', 'Não'],
        complement: 'Quais?',
    },
    {
        id: 39,
        question: 'Já teve passagem pela delegacia?',
        answers: ['Sim', 'Não'],
        complement: 'Nota',
    },
    {
        id: 40,
        question: ' ',
        answers: [],
        complement: 'Qual a sua meta de vida?',
    },
    {
        id: 41,
        question: '',
        answers: [],
        complement: 'Fale sobre você: 1 ponto positivo e 1 ponto negativo:',
    },
    {
        id: 42,
        question: '',
        answers: [],
        complement: 'Sugestão para redução de acidentes no trânsito: ',
    },
    {
        id: 0,
        question: 'Complementos para atividade remunerada como condutor',
        answers: [],
        complement: '',
    },
    {
        id: 43,
        question: 'Já possui experiência como motorista profissional?',
        answers: ['Sim', 'Não'],
        complement: 'Tempo/Carga',
    },
    {
        id: 44,
        question: 'Já passou por alguma situação de perigo no trânsito?',
        answers: ['Sim', 'Não'],
        complement: 'Qual?',
    },
    {
        id: 45,
        question: '',
        answers: [],
        complement: 'Fale sobre uma situação que te deixou mais irritado no trânsito: ',
    },
    {
        id: 46,
        question: 'Já sofreu acidente de trânsito?',
        answers: ['Sim', 'Não'],
        complement: 'Qual?',
    },
    {
        id: 47,
        question: 'Teve multas, pontos na CNH',
        answers: ['Sim', 'Não'],
        complement: 'Por quê?',
    },
    {
        id: 48,
        question: 'CNH já foi apreendida ou cassada?',
        answers: ['Sim', 'Não'],
        complement: 'Porque/quando?',
    },
    {
        id: 49,
        question: 'Usa algum estimulante para dirigir? ',
        answers: ['Sim', 'Não'],
        complement: 'Qual?',
    },
    {
        id: 50,
        question: '',
        answers: [],
        complement: 'Quando está dirigindo e recebe uma ligação ou percebe que chegou uma mensagem no celular, como reage?',
    },
    {
        id: 51,
        question: '',
        answers: [],
        complement: 'Quando você é convidado para um evento em que você fará uso de bebida alcoólica, como se organiza, com relação à condução do veículo?',
    },
]
