export const questions = [
    {
        id: 0,
        question: 'Condições para realização da avaliação',
        answers: [],
        complement: '',
    },
    {
        id: 1,
        question: 'Está descansado hoje?',
        answers: ['sim', 'não'],
        complement: 'Por quê?',
    },
    {
        id: 2,
        question: 'Dormiu bem esta noite?',
        answers: ['sim', 'não'],
        complement: 'Por quê?',
    },
    {
        id: 3,
        question: 'Está alimentado?',
        answers: ['sim', 'não'],
        complement: '',
    },
    {
        id: 4,
        question: 'Fez uso de bebida alcoolica nas últimas horas?',
        answers: ['sim', 'não'],
        complement: '',
    },
    {
        id: 5,
        question: 'Fez uso de alguma medicação ontem/hoje?',
        answers: ['sim', 'não'],
        complement: '',
    },
    {
        id: 6,
        question: 'Faz uso de lentes corretivas/óculos?',
        answers: ['sim', 'não'],
        complement: '',
    },
    {
        id: 7,
        question: 'Considera-se em boas condições para realização da avaliação psicológica?',
        answers: ['sim', 'não'],
        complement: 'Por quê?',
    },
    {
        id: 0,
        question: 'Histórico Familiar',
        answers: [],
        complement: '',
    },
    {
        id: 8,
        question: 'Estado Civil',
        answers: ['Divorciado', 'Viúvo', 'Solteiro', 'Casado', 'União Estável'],
        complement: '',
    },
    {
        id: 9,
        question: 'Possui filhos?',
        answers: ['Sim', 'Não'],
        complement: '',
    },
    {
        id: 10,
        question: '',
        answers: [''],
        complement: 'Com quem você mora?',
    },
    {
        id: 11,
        question: 'Está enfrentando problemas familiares?',
        answers: ['Sim', 'Não'],
        complement: 'Quais?',
    },
    {
        id: 12,
        question: 'Possui irmãos?',
        answers: ['Sim', 'Não'],
        complement: 'Quantos?',
    },
    {
        id: 13,
        question: '',
        answers: [''],
        complement: 'Como é seu relacionamento com sua família?',
    },
    {
        id: 14,
        question: 'Na família existe alguém que necessite de cuidados médicos ou psicológicos? ',
        answers: ['Sim', 'Não'],
        complement: 'Nota',
    },
    {
        id: 0,
        question: 'Vida Profissional',
        answers: [],
        complement: '',
    },
    {
        id: 15,
        question: 'Estado Civil',
        answers: ['Divorciado', 'Viúvo', 'Solteiro', 'Casado', 'União Estável'],
        complement: '',
    },
    {
        id: 16,
        question: 'Estado Civil',
        answers: ['Divorciado', 'Viúvo', 'Solteiro', 'Casado', 'União Estável'],
        complement: '',
    },
    {
        id: 17,
        question: 'Estado Civil',
        answers: ['Divorciado', 'Viúvo', 'Solteiro', 'Casado', 'União Estável'],
        complement: '',
    },
    {
        id: 18,
        question: 'Estado Civil',
        answers: ['Divorciado', 'Viúvo', 'Solteiro', 'Casado', 'União Estável'],
        complement: '',
    },
]